chore(gitHooks): add tests to pre-commit and pre-push

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -13,3 +13,9 @@ if [[ $? -ne 0 ]]; then
   echo 'JavaScript Standard Style errors were detected. Aborting commit.'
   exit 1
 fi
+
+./node_modules/.bin/ava -v -m 'util*'
+if [[ $? -ne 0 ]]; then
+  echo 'AVA integration tests errors were detected. Aborting push.'
+  exit 1
+fi
